### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by vesalucsf** [mwdhont/SimCLRv1-keras-tensorflow#3]
The following error is generated by both: `SimCLR.train(data_train, data_val, epochs = 5)` and y`_predict_test_before = SimCLR.predict(data_test)`.

I could not trace it why this happens. Even though I installed the same version of TF and Keras as suggested in the requirements file. 

Another question is that why your data generator gives a final output with 5 dimensions for images, since the VGG takes the `b x w x h x c` as the input only. 

Output for one batch:
`batch shape: (64, 1, 80, 80, 3), label_shape: (32, 128)`

Thanks.

**Comment by mwdhont** [comment]
Hi Vesalucsf,

Thanks for checking the code thoroughly. 

1. Could you provide some more details on the error? My first feeling is that it is likely to be related to the opencv package? cv.imread is used to read the images in the datagenerator, is your path in this function correct etc?

2. You're correct that the dimensions of the SimCLR-DataGenerator might seem a bit odd at first. This is linked due to the chosen implementation. The first 64 refers to 32 images which are each twice randomly transformed ->64. Next, the 1 is just to pass one single image through the VGG-network each time and get the feature representation for that image. 80x80x3 are obviously the img-dimensions. 
The output-matrix represents the dot product of the projected feature vectors. So the 32 images x the 4 times 32 images against which they are checked. In an ideal case, this matrix should look like [I|O|I|O], as further explained in the ReadMe. and the original paper.

Hope this helps,
Michiel

**Comment by luckylulin-aaron** [comment]
I came across the same error too
